import os
from dotenv import load_dotenv
load_dotenv()

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN", "your_default_telegram_token")
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
DATABASE_URL = os.getenv("DATABASE_URL")
YOOKASSA_SHOP_ID = os.getenv("YOOKASSA_SHOP_ID")
YOOKASSA_SECRET_KEY = os.getenv("YOOKASSA_SECRET_KEY", "your_default_yookassa_secret_key")
TEST_CHANNEL_ID = int(os.getenv("TEST_CHANNEL_ID"))
PAYMENT_PROVIDER_TOKEN = os.getenv("PAYMENT_PROVIDER_TOKEN")
PAYMENT_RETURN_URL = os.getenv("PAYMENT_RETURN_URL")
YOOKASSA_URL = os.getenv("YOOKASSA_URL")
CHANNEL_USERNAME = os.getenv("CHANNEL_USERNAME")
API_ID = os.getenv("API_ID")
API_HASH = os.getenv("API_HASH")
PHONE_NUMBER= os.getenv('PHONE_NUMBER')
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_DB = os.getenv("POSTGRES_DB")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", )
BITLY_ACCESS_TOKEN = os.getenv("BITLY_ACCESS_TOKEN")
CUTTLY_API_KEY = os.getenv("CUTTLY_API_KEY")
SENTRY_DSN = os.getenv("SENTRY_DSN")

ZENROWS_API_KEY = os.getenv("ZENROWS_API_KEY")