"""Initial migration

Revision ID: 47d4c57f77e4
Revises: 
Create Date: 2025-03-10 14:31:32.596452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47d4c57f77e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('invoice_message_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'payments', ['invoice_message_id'])
    op.add_column('posts', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'created_at')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'invoice_message_id')
    # ### end Alembic commands ###
